name: Publish Helm Charts

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@30cbe9f13b7848656014f06761023041de9b514b # v1.9.1
    with:
      charts-dir: 'charts'
      helm-repos: |
        longhorn https://charts.longhorn.io
      subpath: 'talos'
